### ISSUE TITLE
Consider using `eslint-plugin-jsdoc`

### ISSUE THREAD

**Issue by jthegedus** [jthegedus/svelte-adapter-firebase#142]
I am sure the quality of the JSDoc could be improved. We should investigate using this eslint plugin to help:

- https://github.com/gajus/eslint-plugin-jsdoc

**Comment by jthegedus** [comment]
Got this error :shrug: 

```shell
svelte-adapter-firebase on  main [$!] is 📦 v0.12.0 via ⬢ v14.17.5 took 4s 
➜ pnpm run test

> svelte-adapter-firebase@0.12.0 test /home/jthegedus/projects/svelte-adapter-firebase
> xo && uvu tests/unit

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/jthegedus/projects/svelte-adapter-firebase/node_modules/.pnpm/array-union@3.0.1/node_modules/array-union/index.js
require() of ES modules is not supported.
require() of /home/jthegedus/projects/svelte-adapter-firebase/node_modules/.pnpm/array-union@3.0.1/node_modules/array-union/index.js from /home/jthegedus/projects/svelte-adapter-firebase/node_modules/.pnpm/@typescript-eslint+typescript-estree@4.31.1_typescript@4.4.3/node_modules/@typescript-eslint/typescript-estree/node_modules/globby/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/jthegedus/projects/svelte-adapter-firebase/node_modules/.pnpm/array-union@3.0.1/node_modules/array-union/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/jthegedus/projects/svelte-adapter-firebase/node_modules/.pnpm/array-union@3.0.1/node_modules/array-union/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jthegedus/projects/svelte-adapter-firebase/node_modules/.pnpm/@typescript-eslint+typescript-estree@4.31.1_typescript@4.4.3/node_modules/@typescript-eslint/typescript-estree/node_modules/globby/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
 ERROR  Test failed. See above for more details.

```
