### ISSUE TITLE
bug: no matching export error during `npm run build`

### ISSUE THREAD

**Issue by edman** [jthegedus/svelte-adapter-firebase#151]
### Describe the Bug

`npm run build` gives an error:

```
> Using svelte-adapter-firebase
 > .svelte-kit/output/server/app.js:11988:14: warning: Using direct eval with a bundler is not recommended and may cause problems (more info: https://esbuild.github.io/link/direct-eval)
    11988 │     var mod = eval("quire".replace(/^/, "re"))(moduleName);
          ╵               ~~~~

 > .svelte-kit/output/server/app.js:20:7: error: No matching export in "node_modules/tslib/modules/index.js" for import "default"
    20 │ import require$$0$6, { __values, __read, __awaiter, __generator, __spreadArray, __rest } from "tslib";
       ╵        ~~~~~~~~~~~~

> Build failed with 1 error:
.svelte-kit/output/server/app.js:20:7: error: No matching export in "node_modules/tslib/modules/index.js" for import "default"
Error: Build failed with 1 error:
.svelte-kit/output/server/app.js:20:7: error: No matching export in "node_modules/tslib/modules/index.js" for import "default"
    at failureErrorWithLog (/Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:1475:15)
    at /Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:1133:28
    at runOnEndCallbacks (/Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:1051:65)
    at buildResponseToResult (/Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:1131:7)
    at /Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:1240:14
    at /Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:611:9
    at handleIncomingPacket (/Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:708:9)
    at Socket.readFromStdout (/Users/edman/projects/uzme/uzme-svelte/node_modules/svelte-adapter-firebase/node_modules/esbuild/lib/main.js:578:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
```

### Steps to Reproduce

I couldn't reproduce on an empty sveltekit app, but happens every time at my project.

### Expected Behaviour

svelte-adapter-firebase prints the cloud function I should paste in index.ts.

### svelte-adapter-firebase version

0.13.1

### sveltejs/kit version

1.0.0-next.180

**Comment by edman** [comment]
The problem disappeared after I fixed my use of the client firebase sdks in SSR.
