### ISSUE TITLE
bug: helloworld sveltekit with helloworld firebase ENOENT: no such file or directory

### ISSUE THREAD

**Issue by janitha09** [jthegedus/svelte-adapter-firebase#167]
### Describe the Bug

using the latest version of this adapter gives the error below
```sh
$ npm run build

> sympler-webapp-test@0.0.1 build
> svelte-kit build

vite v2.9.9 building for production...
transforming (11) .svelte-kit/generated/client-manifest.js
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
✓ 14 modules transformed.
.svelte-kit/output/client/_app/manifest.json                               1.17 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-1e5b23fa.js           0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-61066a60.js                    1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/index.svelte-b63b29a9.js              0.80 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/chunks/index-c3650d4a.js                    6.84 KiB / gzip: 2.79 KiB
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-70ae0eee.css   3.14 KiB / gzip: 1.28 KiB
.svelte-kit/output/client/_app/start-69f37e2d.js                           23.19 KiB / gzip: 8.69 KiB
vite v2.9.9 building SSR bundle for production...
✓ 12 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                       1.13 KiB
.svelte-kit/output/server/index.js                            75.64 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js    0.25 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js   0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js       0.32 KiB
.svelte-kit/output/server/chunks/index-5f038599.js            2.31 KiB
.svelte-kit/output/server/chunks/hooks-1c45ba0b.js            0.00 KiB

Run npm run preview to preview your production build locally.

> Using svelte-adapter-firebase
> Error: Required "hosting[].rewrites[]" does not contain a config with "source":"**" and either "function":"<func_name>" or "run":{...} entries
    at parseFirebaseConfiguration (file:///workspaces/sveltekit/Sympler-WebApp-Test/node_modules/svelte-adapter-firebase/src/utils.js:143:9)
    at adapt (file:///workspaces/sveltekit/Sympler-WebApp-Test/node_modules/svelte-adapter-firebase/src/index.js:26:35)
    at adapt (file:///workspaces/sveltekit/Sympler-WebApp-Test/node_modules/@sveltejs/kit/dist/chunks/index4.js:178:8)
    at file:///workspaces/sveltekit/Sympler-WebApp-Test/node_modules/@sveltejs/kit/dist/cli.js:981:11
```

### Steps to Reproduce

npm init svelte Sympler-WebApp-Test
npx svelte-add@latest tailwindcss
npm install --save-dev svelte-adapter-firebase
firebase init
npm run build

package.json

```json
{
	"name": "sympler-webapp-test",
	"version": "0.0.1",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"package": "svelte-kit package",
		"preview": "svelte-kit preview",
		"prepare": "svelte-kit sync",
		"test": "playwright test",
		"check": "svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
		"format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
	},
	"devDependencies": {
		"@playwright/test": "^1.21.0",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"@typescript-eslint/eslint-plugin": "^5.10.1",
		"@typescript-eslint/parser": "^5.10.1",
		"autoprefixer": "^10.4.4",
		"eslint": "^8.12.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.12",
		"postcss-load-config": "^3.1.4",
		"prettier": "^2.5.1",
		"prettier-plugin-svelte": "^2.5.0",
		"svelte": "^3.44.0",
		"svelte-adapter-firebase": "^0.14.0",
		"svelte-check": "^2.2.6",
		"svelte-preprocess": "^4.10.5",
		"tailwindcss": "^3.0.23",
		"tslib": "^2.3.1",
		"typescript": "~4.6.2"
	},
	"type": "module"
}
```
```typescript
import firebase from 'svelte-adapter-firebase';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		preprocess({
			postcss: true
		})
	],

	kit: {
		adapter: firebase()
	}
};

export default config;
```

firebase.json

```json
{
  "emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 8080
    },
    "hosting": {
      "port": 3000
    },
    "ui": {
      "enabled": true
    }
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

### Expected Behaviour

the public folder gets the required files so
firebase emulators:start can host the site locally

### svelte-adapter-firebase version

0.14.0

### sveltejs/kit version

1.0.0-next.336

**Comment by Nushio** [comment]
Make sure your firebase.json has either a 'function' or 'run' as part of the hosting rewrites subsection.

`Error: Required "hosting[].rewrites[]" does not contain a config with "source":"**" and either "function":"<func_name>" or "run":{...} entries`

"rewrites": [
      {
        "source": "**",
        ~~"destination": "/index.html"~~
       "function": "ssr"
      }
    ]

**Comment by janitha09** [comment]
I just might not understand what this adapter is for. 
After running this `firestore init functions` and then modifying the firestore.json file to hack the errors as below
```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html",
        "function": "ssrServer"
      }
    ]
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 8080
    },
    "hosting": {
      "port": 3000
    },
    "ui": {
      "enabled": true
    }
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "source": "functions"
  }
}
```

leads to this error

```sh
$ npm run build

> sympler-webapp-test@0.0.1 build
> svelte-kit build

vite v2.9.9 building for production...
transforming (10) .svelte-kit/generated/client-manifest.js
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
✓ 14 modules transformed.
.svelte-kit/output/client/_app/manifest.json                               1.17 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-1e5b23fa.js           0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-61066a60.js                    1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/index.svelte-b63b29a9.js              0.80 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/chunks/index-c3650d4a.js                    6.84 KiB / gzip: 2.79 KiB
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-70ae0eee.css   3.14 KiB / gzip: 1.28 KiB
.svelte-kit/output/client/_app/start-45d77d60.js                           23.19 KiB / gzip: 8.69 KiB
vite v2.9.9 building SSR bundle for production...
✓ 12 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                       1.13 KiB
.svelte-kit/output/server/index.js                            75.64 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js    0.25 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js   0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js       0.32 KiB
.svelte-kit/output/server/chunks/index-5f038599.js            2.31 KiB
.svelte-kit/output/server/chunks/hooks-1c45ba0b.js            0.00 KiB

Run npm run preview to preview your production build locally.

> Using svelte-adapter-firebase
> Error reading Cloud Function entrypoint file: /workspaces/sveltekit/Sympler-WebApp-Test/functions/lib/index.js. ENOENT: no such file or directory, open '/workspaces/sveltekit/Sympler-WebApp-Test/functions/lib/index.js'
    at adapt (file:///workspaces/sveltekit/Sympler-WebApp-Test/node_modules/svelte-adapter-firebase/src/index.js:91:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async adapt (file:///workspaces/sveltekit/Sympler-WebApp-Test/node_modules/@sveltejs/kit/dist/chunks/index4.js:178:2)
    at async file:///workspaces/sveltekit/Sympler-WebApp-Test/node_modules/@sveltejs/kit/dist/cli.js:981:5
```

**Comment by janitha09** [comment]
> Make sure your firebase.json has either a 'function' or 'run' as part of the hosting rewrites subsection.
> 
> `Error: Required "hosting[].rewrites[]" does not contain a config with "source":"**" and either "function":"<func_name>" or "run":{...} entries`
> 
> ```
> "rewrites": [
>       {
>         "source": "**",
>         ~~"destination": "/index.html"~~
>        "function": "ssr"
>       }
>     ]
> ```

**Comment by Nushio** [comment]
Do you have a folder named `functions` on your `Sympler-WebApp-Test` folder? (as defined on the functions.source section of firebase.json)

The error, " ENOENT: no such file or directory" denotes that it can't find a folder named 'lib' and a file named 'index.js' inside the functions folder. Creating them, even if empty, will solve the build problems.

> I just might not understand what this adapter is for.

SvelteKit allows you to pre-compile / pre-render your Svelte app. 

This adapter allows you to serve those pre-compiled pages on a firebase function (or via Cloud Run), and using the hosting.rewrites section of firebase.json, use the SSR function to render your page initially to your user instead of displaying the static, pre-compiled pages that sveltekit generated.

**Comment by janitha09** [comment]
It was not there because I chose the typescript opetion when I initialized the function.

A vanilla ts function fails like so.

```sh
$ firebase emulators:start
i  emulators: Starting emulators: functions, firestore
⚠  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, database, hosting, pubsub, storage
✔  functions: Using node@16 from host.
i  firestore: Firestore Emulator logging to firestore-debug.log
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/workspaces/sveltekit/fb-func-hw-ts/functions" for Cloud Functions...
i  emulators: Shutting down emulators.
i  ui: Stopping Emulator UI
⚠  Emulator UI has exited upon receiving signal: SIGINT
i  functions: Stopping Functions Emulator
i  firestore: Stopping Firestore Emulator
i  hub: Stopping emulator hub
i  logging: Stopping Logging Emulator

Error: There was an error reading functions/package.json:

 functions/lib/index.js does not exist, can't deploy Cloud Functions
```

**Comment by Nushio** [comment]
Yes, Vanilla Typescript needs to be transpiled to Javascript so that it generates the lib/main.js file. Just run npm run build on the functions folder at least once, before running npm run build on your sveltekit project.
